routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\MyProfileController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\RoleController;



Route::prefix('admin')->name('admin.')->group(function () {
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('users', UserController::class);

    Route::get('users/{id}/my-profiles',         [MyProfileController::class, 'index'])->name('my-profile');
    Route::get('users/{id}/my-profiles-edit',    [MyProfileController::class, 'profile'])->name('my-profile.edit');
    Route::put('users/{id}/my-profiles-update',  [MyProfileController::class, 'updateProfile'])->name('my-profile.update');
    Route::get('users/{id}/password',            [MyProfileController::class, 'Password'])->name('password');
    Route::put('users/{id}/change-password',     [MyProfileController::class, 'changePassword'])->name('change-password');

    Route::resource('permission', PermissionController::class);
    Route::resource('role', RoleController::class);
});

routes/web.php
<?php

// use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    return view('welcome');
});

// Route::get('export/excel', [UserController::class, 'exportExcel'])->name('excel');
// Route::get('export/csv', [UserController::class, 'exportCsv'])->name('csv');
// Route::get('export/pdf', [UserController::class, 'exportPdf'])->name('pdf');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

require __DIR__.'/admin.php';

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\RoleRequest;
use App\Repositories\PermissionRepository;
use App\Repositories\RoleRepository;

class RoleController extends Controller
{

    protected $roleRepository;
    protected $permissionRepository;

    public function __construct(RoleRepository $roleRepository,
                                PermissionRepository $permissionRepository)
    {
        $this->repo = $roleRepository;
        $this->permiss = $permissionRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles = $this->repo->getAll();
        return view('admin.roles.index', compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permission = $this->permiss->getAll();
        return view('admin.roles.form', compact('permission'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RoleRequest $request)
    {
        $this->repo->store();
        return redirect()->to('admin/role')->withSuccess('You have successfully added a new roles');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $permission         = $this->repo->getAllPermission();
        $permissionByRoles  = $this->repo->permissionByRoles($id);
        $role               = $this->repo->getById($id);

        return view('admin.roles.form', compact('permission','permissionByRoles', 'role'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(RoleRequest $request, $id)
    {
        $this->repo->updateById($id);
        return redirect()->back()->withSuccess('You have successfully updated a roles');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->repo->delete($id);
        return redirect()->to('admin/role')->withSuccess('You have successfully deleted a roles');
    }
}

resources/views/admin/roles/form.blade.php
@extends('layouts.admin.app')
@section('sub-title', 'Profile')
@section('location')  
    @if (get_action_name() == 'create')
    Add Roles
    @else
    Edit Roles
    @endif
@endsection
@push('links')
<style>
    .isDisabled {
        cursor: not-allowed;
        opacity: 0.5;
        color: red;
    }
</style>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css"> 
@endpush
@section('content') 
<div class="card">
    <form action="{{
    route((get_action_name() == 'create')? 'admin.role.store': 'admin.role.update', [
        'role'   => $role ?? '',
        ])
    }}" 
    method="POST">
    @csrf
    @method((get_action_name() == 'create') ? 'POST': 'PUT')

    <div class="card-header">
        <h4><a href="{{route('admin.role.index')}}" class="btn btn-warning">Back</a></h4>
        @if (!(get_action_name() == 'create'))
        <div class="card-header-action">
            <div class="dropdown">
              <a href="#" class="dropdown-toggle btn btn-primary" data-toggle="dropdown" aria-expanded="false">Advanced</a>
              <div class="dropdown-menu dropdown-menu-right" x-placement="bottom-end" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(70px, 25px, 0px);">
                @role('super_admin|admin')
                <a href="#" class="dropdown-item has-icon" data-toggle="modal" data-target="#delete{{$role->id}}"><i class="fas fa-trash"></i>Delete Roles</a>
                @else
                <a href="javascript:void(0)" class="dropdown-item has-icon isDisabled"><i class="fas fa-user-times"></i>You don't have access</a>
                @endrole
              </div>
            </div>
        </div>
        @endif
    </div>
    <div class="card-body">
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" name="name" class="form-control" placeholder="Create this name.." value="{{ $role->name ?? ''}}">
        </div>
        <div class="form-group">
            <label for="display_name">Display Name</label>
            <input type="text" name="display_name" class="form-control" placeholder="Create this display name.." value="{{ $role->display_name ?? ''}}">
        </div>
        <div class="form-group">
            <label for="guard_name">Guard Name</label>
            <select class="selectpicker form-control" name="guard_name" id="guard_name">
                <option value="web" selected>Web</option>
            </select>
        </div>
        <div class="section-title mt-0">Select Permission</div>
        @if (get_action_name() == 'create')
            @foreach ($permission as $permis)
            <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="permissions[]" value="{{$permis->name}}" id="{{$permis->id}}">
                <label class="custom-control-label" for="{{$permis->id}}">{{$permis->display_name}}</label>
            </div>
            @endforeach
        @else
            @foreach ($permission as $permis)
            <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="permissions[]" value="{{$permis->name}}" id="{{$permis->id}}"
                @foreach ($permissionByRoles as $item)
                    @if ($permis->name == $item)
                        checked
                    @endif
                @endforeach
                >   
                <label class="custom-control-label" for="{{$permis->id}}">{{$permis->display_name}}</label>
            </div>
            @endforeach
        @endif
        </div>
    <div class="card-footer">
      <button type="submit" class="btn btn-primary">
          {{(get_action_name() == 'create') ? 'Submit': 'Update'}}
      </button>
    </div>
    </form>
</div>
@endsection
@section('modal')
<!-- Modal -->
<div class="modal fade" id="delete{{$role->id ?? ''}}" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title" id="exampleModalLabel" style="color: #6777ef">Confirmation:</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <h4 class="modal-title">Are you sure to remove this role?</h4>
            <h4 class="modal-title text-center" style="color: red; text-decoration: underline">{{$role->display_name ?? ''}}</h4>
        </div>
        <div class="modal-footer">
            <form action="{{ route('admin.role.destroy', $role->id ?? '') }}" method="POST">
                @csrf
                @method('delete')
                <button type="button" class="btn btn-warning" data-dismiss="modal">No, and Close</button>
                <button type="submit" class="btn btn-danger">Sure, and Delete</button>
            </form>
        </div>
    </div>
  </div>
</div>
@endsection
@push('scripts')
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
@endpush

resources/views/admin/roles/index.blade.php
@extends('layouts.admin.app')
@section('sub-title', 'Roles')
@section('location', 'Roles')
@push('css')
@endpush
@section('content') 

    <div class="card">
        <div class="card-header">
            <h4><a href="{{route('admin.role.create')}}" class="btn btn-info">Create Roles</a></h4>
            <div class="card-header-action">
              <form action="{{route('admin.role.index')}}" method="get">
                <div class="input-group">
                  <input type="text" name="filter[name]" class="form-control" placeholder="Search by name" value="">
                  <div class="input-group-btn">
                    <button type="submit" class="btn btn-primary"><i class="fas fa-search"></i></button>
                  </div>
                </div>
              </form>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
              <table class="table table-striped" id="table-2">
                <thead>
                  <tr>
                    <th class="text-center">
                      <div class="custom-checkbox custom-control">
                        <input type="checkbox" data-checkboxes="mygroup" data-checkbox-role="dad" class="custom-control-input" id="checkbox-all" onclick="toggle(this);">
                        <label for="checkbox-all" class="custom-control-label">&nbsp;</label>
                      </div>
                    </th>
                    <th>Name</th>
                    <th>Display Name</th>
                    <th>Guard Name</th>
                    <th>Created on</th>
                    <th>Action</th>
                  </tr>
                </thead>
                @if (count($roles) > 0)
                @foreach ($roles as $r)
                <tbody>
                  <tr>
                    <td>
                      <div class="custom-checkbox custom-control">
                        <input type="checkbox" data-checkboxes="mygroup" class="custom-control-input" id="checkbox-1">
                        <label for="checkbox-1" class="custom-control-label">&nbsp;</label>
                      </div>
                    </td>
                    <td>{{$r->name}}</td>
                    <td>{{$r->display_name}}</td>
                    <td>{{$r->guard_name}}</td>
                    <td>{{$r->created_at->format('d/m/Y')}}</td>
                    <td>
                      <a href="#" class="btn btn-sm btn-info trigger--fire-modal-6" data-toggle="modal" data-target="#role{{$r->id}}">Detail</a>
                      <a href="{{route('admin.role.edit', $r->id)}}" class="btn btn-sm btn-primary">Edit</a>
                    </td>
                  </tr>
                </tbody>
                @endforeach
                @else
                <td colspan="9" class="text-center"><h4>Roles is not Found!</h4></td>
                @endif
            </table>
          </div>
        </div>
    </div>

    <!-- Pagination -->
    <nav aria-label="Page navigation example">
      <ul class="pagination">
        <li class="page-item">
          {{$roles->links('vendor.pagination.bootstrap-4')}}
        </li>
      </ul>
    </nav>
@endsection
@section('modal')
<!-- Modal -->
@foreach ($roles as $r)
<div class="modal fade" id="role{{$r->id}}" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="exampleModalLabel" style="color: #6777ef">Details:</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="form-group row">
          <label for="name" class="col-sm-2 col-form-label">Name</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" value="{{$r->name}}" disabled>
          </div>
        </div>
        <div class="form-group row">
          <label for="username" class="col-sm-2 col-form-label">Display Name</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" value="{{$r->display_name}}" disabled>
          </div>
        </div>
        <div class="form-group row">
          <label for="inputEmail3" class="col-sm-2 col-form-label">Guard Name</label>
          <div class="col-sm-10">
            <input type="email" class="form-control" value="{{$r->guard_name}}" disabled>
          </div>
        </div>
        <div class="form-group row">
          <label for="inputEmail3" class="col-sm-2 col-form-label">Permission</label>
          <div class="col-sm-10">
            <input type="email" class="form-control" 
            value=""
             disabled>
          </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="status">Create on</label>
                <input type="text" name="status" class="form-control" 
                value="{{$r->created_at}}"
                disabled>
            </div>
            <div class="form-group col-md-6">
                <label for="status">Update on</label>
                <input type="text" name="status" class="form-control" 
                value="{{$r->updated_at}}"
                disabled>
            </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
        <a href="{{route('admin.role.edit', $r->id)}}" class="btn btn-primary">Edit</a>
      </div>
    </div>
  </div>
</div>
@endforeach
@endsection
@push('scripts')
<script>
// Selected All Cheackbox
function toggle(source) {
    var checkboxes = document.querySelectorAll('input[type="checkbox"]');
    for (var i = 0; i < checkboxes.length; i++) {
        if (checkboxes[i] != source)
            checkboxes[i].checked = source.checked;
    }
};
</script>
@endpush