routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\MyProfileController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\RoleController;



Route::prefix('admin')->name('admin.')->group(function () {
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('users', UserController::class);

    Route::get('users/{id}/my-profiles',         [MyProfileController::class, 'index'])->name('my-profile');
    Route::get('users/{id}/my-profiles-edit',    [MyProfileController::class, 'profile'])->name('my-profile.edit');
    Route::put('users/{id}/my-profiles-update',  [MyProfileController::class, 'updateProfile'])->name('my-profile.update');
    Route::get('users/{id}/password',            [MyProfileController::class, 'Password'])->name('password');
    Route::put('users/{id}/change-password',     [MyProfileController::class, 'changePassword'])->name('change-password');

    Route::resource('permission', PermissionController::class);
    Route::resource('role', RoleController::class);
});

routes/web.php
<?php

// use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    return view('welcome');
});

// Route::get('export/excel', [UserController::class, 'exportExcel'])->name('excel');
// Route::get('export/csv', [UserController::class, 'exportCsv'])->name('csv');
// Route::get('export/pdf', [UserController::class, 'exportPdf'])->name('pdf');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

require __DIR__.'/admin.php';

app/Http/Controllers/Admin/PermissionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\PermissionRequest;
use App\Repositories\PermissionRepository;

class PermissionController extends Controller
{


    protected $permissionRepository;

    public function __construct(PermissionRepository $permissionRepository)
    {
        $this->repo = $permissionRepository;
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $permission = $this->repo->getAll();
        return view('admin.permission.index', compact('permission'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.permission.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PermissionRequest $request)
    {
        $this->repo->store();
        return redirect()->to('admin/permission')->withSuccess('You have successfully added a new permission');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $permission = $this->repo->getById($id);
        return view('admin.permission.form', compact('permission'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PermissionRequest $request, $id)
    {
        $this->repo->updateById($id);
        return redirect('admin/permission')->withSuccess('You have successfully updated a permission');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->repo->delete($id);
        return redirect('admin/permission')->withSuccess('You have successfully deleted a permission');
    }
}

resources/views/admin/permission/form.blade.php
@extends('layouts.admin.app')
@section('sub-title', 'Profile')

@section('location')  
@if (get_action_name() == 'create')
Add Permission
@else
Edit Permission
@endif
@endsection

@push('links')
<style>
    .isDisabled {
        cursor: not-allowed;
        opacity: 0.5;
        color: red;
    }
</style>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css"> 
@endpush
@section('content') 
<div class="card">
    <form action="{{
    route((get_action_name() == 'create')? 'admin.permission.store': 'admin.permission.update', [
        'permission'   => $permission ?? '',
        ])
    }}" 
    method="POST">
    @csrf
    @method((get_action_name() == 'create') ? 'POST': 'PUT')

    <div class="card-header">
        <h4><a href="{{route('admin.permission.index')}}" class="btn btn-warning">Back</a></h4>
        @if (!(get_action_name() == 'create'))
        <div class="card-header-action">
            <div class="dropdown">
              <a href="#" class="dropdown-toggle btn btn-primary" data-toggle="dropdown" aria-expanded="false">Advanced</a>
              <div class="dropdown-menu dropdown-menu-right" x-placement="bottom-end" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(70px, 25px, 0px);">
                @role('super_admin|admin')
                <a href="#" class="dropdown-item has-icon" data-toggle="modal" data-target="#delete{{$permission->id}}"><i class="fas fa-trash"></i>Delete Permission</a>
                @else
                <a href="javascript:void(0)" class="dropdown-item has-icon isDisabled"><i class="fas fa-user-times"></i>You don't have access</a>
                @endrole
              </div>
            </div>
        </div>
        @endif
    </div>
    <div class="card-body">
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" name="name" class="form-control" placeholder="Create this name.." value="{{ $permission->name ?? ''}}">
        </div>
        <div class="form-group">
            <label for="display_name">Display Name</label>
            <input type="text" name="display_name" class="form-control" placeholder="Create this display name.." value="{{ $permission->display_name ?? ''}}">
        </div>
        <div class="form-group">
            <label for="guard_name">Guard Name</label>
            <input type="text" name="guard_name" class="form-control" placeholder="Create this guard name.." value="{{ $permission->guard_name ?? ''}}">
        </div>
    </div>
    <div class="card-footer">
      <button type="submit" class="btn btn-primary">
          {{(get_action_name() == 'create') ? 'Submit': 'Update'}}
      </button>
    </div>
    </form>
</div>
@endsection
@section('modal')
<!-- Modal -->
<div class="modal fade" id="delete{{$permission->id ?? ''}}" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title" id="exampleModalLabel" style="color: #6777ef">Confirmation:</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <h4 class="modal-title">Are you sure to remove this permission?</h4>
            <h4 class="modal-title text-center" style="color: red; text-decoration: underline">{{$permission->display_name ?? ''}}</h4>
        </div>
        <div class="modal-footer">
            <form action="{{ route('admin.permission.destroy', $permission->id ?? '') }}" method="POST">
                @csrf
                @method('delete')
                <button type="button" class="btn btn-warning" data-dismiss="modal">No, and Close</button>
                <button type="submit" class="btn btn-danger">Sure, and Delete</button>
            </form>
        </div>
    </div>
  </div>
</div>
@endsection
@push('scripts')
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
@endpush

resources/views/admin/permission/index.blade.php
@extends('layouts.admin.app')
@section('sub-title', 'Permission')
@section('location', 'Permission')
@push('css')
@endpush
@section('content') 

    <div class="card">
        <div class="card-header">
            <h4><a href="{{route('admin.permission.create')}}" class="btn btn-info">Create Permission</a></h4>
            <div class="card-header-action">
              <form action="{{route('admin.permission.index')}}" method="get">
                <div class="input-group">
                  <input type="text" name="filter[name]" class="form-control" placeholder="Search by name" value="">
                  <div class="input-group-btn">
                    <button type="submit" class="btn btn-primary"><i class="fas fa-search"></i></button>
                  </div>
                </div>
              </form>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
              <table class="table table-striped" id="table-2">
                <thead>
                  <tr>
                    <th class="text-center">
                      <div class="custom-checkbox custom-control">
                        <input type="checkbox" data-checkboxes="mygroup" data-checkbox-role="dad" class="custom-control-input" id="checkbox-all" onclick="toggle(this);">
                        <label for="checkbox-all" class="custom-control-label">&nbsp;</label>
                      </div>
                    </th>
                    <th>Name</th>
                    <th>Display Name</th>
                    <th>Guard Name</th>
                    <th>Created on</th>
                    <th>Action</th>
                  </tr>
                </thead>
                @if (count($permission) > 0)
                @foreach ($permission as $p)
                <tbody>
                  <tr>
                    <td>
                      <div class="custom-checkbox custom-control">
                        <input type="checkbox" data-checkboxes="mygroup" class="custom-control-input" id="checkbox-1">
                        <label for="checkbox-1" class="custom-control-label">&nbsp;</label>
                      </div>
                    </td>
                    <td>{{$p->name}}</td>
                    <td>{{$p->display_name}}</td>
                    <td>{{$p->guard_name}}</td>
                    <td>{{$p->created_at}}</td>
                    <td>
                      <a href="#" class="btn btn-sm btn-info trigger--fire-modal-6" data-toggle="modal" data-target="#permission{{$p->id}}">Detail</a>
                      <a href="{{route('admin.permission.edit', $p->id)}}" class="btn btn-sm btn-primary">Edit</a>
                    </td>
                  </tr>
                </tbody>
                @endforeach
                @else
                <td colspan="9" class="text-center"><h4>Permission is not Found!</h4></td>
                @endif
            </table>
          </div>
        </div>
    </div>

    <!-- Pagination -->
    <nav aria-label="Page navigation example">
      <ul class="pagination">
        <li class="page-item">
          {{$permission->links('vendor.pagination.bootstrap-4')}}
        </li>
      </ul>
    </nav>
@endsection
@section('modal')
<!-- Modal -->
@foreach ($permission as $p)
<div class="modal fade" id="permission{{$p->id}}" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="exampleModalLabel" style="color: #6777ef">Details:</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="form-group row">
          <label for="name" class="col-sm-2 col-form-label">Name</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" value="{{$p->name}}" disabled>
          </div>
        </div>
        <div class="form-group row">
          <label for="username" class="col-sm-2 col-form-label">Display Name</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" value="{{$p->display_name}}" disabled>
          </div>
        </div>
        <div class="form-group row">
          <label for="inputEmail3" class="col-sm-2 col-form-label">Guard Name</label>
          <div class="col-sm-10">
            <input type="email" class="form-control" value="{{$p->guard_name}}" disabled>
          </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="status">Create on</label>
                <input type="text" name="status" class="form-control" 
                value="{{$p->created_at}}"
                disabled>
            </div>
            <div class="form-group col-md-6">
                <label for="status">Update on</label>
                <input type="text" name="status" class="form-control" 
                value="{{$p->updated_at}}"
                disabled>
            </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
        <a href="{{route('admin.permission.edit', $p->id)}}" class="btn btn-primary">Edit</a>
      </div>
    </div>
  </div>
</div>
@endforeach
@endsection
@push('scripts')
<script>
// Selected All Cheackbox
function toggle(source) {
    var checkboxes = document.querySelectorAll('input[type="checkbox"]');
    for (var i = 0; i < checkboxes.length; i++) {
        if (checkboxes[i] != source)
            checkboxes[i].checked = source.checked;
    }
};
</script>
@endpush