routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\MyProfileController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\RoleController;



Route::prefix('admin')->name('admin.')->group(function () {
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('users', UserController::class);

    Route::get('users/{id}/my-profiles',         [MyProfileController::class, 'index'])->name('my-profile');
    Route::get('users/{id}/my-profiles-edit',    [MyProfileController::class, 'profile'])->name('my-profile.edit');
    Route::put('users/{id}/my-profiles-update',  [MyProfileController::class, 'updateProfile'])->name('my-profile.update');
    Route::get('users/{id}/password',            [MyProfileController::class, 'Password'])->name('password');
    Route::put('users/{id}/change-password',     [MyProfileController::class, 'changePassword'])->name('change-password');

    Route::resource('permission', PermissionController::class);
    Route::resource('role', RoleController::class);
});

routes/web.php
<?php

// use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    return view('welcome');
});

// Route::get('export/excel', [UserController::class, 'exportExcel'])->name('excel');
// Route::get('export/csv', [UserController::class, 'exportCsv'])->name('csv');
// Route::get('export/pdf', [UserController::class, 'exportPdf'])->name('pdf');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

require __DIR__.'/admin.php';

resources/views/layouts/admin/components/content.blade.php
@section('sub-title', 'Dashboard')
@section('location', 'Dashboard')
<div class="main-content">
    <section class="section">
    <div class="section-header">
        <div class="col-sm-6">
            <h1>@yield('location')</h1>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active">@yield('location')</li>
            </ol>
        </div>
    </div>
    @yield('content')
    </section>
    @yield('modal')
</div>

resources/views/layouts/admin/components/footer.blade.php
<footer class="main-footer">
    <div class="footer-left">
        Copyright &copy; 2021 by <a href="https://farghani.com/">Agung Prasetyo</a> <div class="bullet"></div> Thanks and Design By <a href="https://nauval.in/">Muhamad Nauval Azhar</a>
    </div>
    <div class="footer-right">
    
    </div>
</footer>

resources/views/layouts/admin/components/header.blade.php
<!-- General CSS Files -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

<!-- Template CSS -->
<link rel="stylesheet" href="{{ asset('assets/css/custom.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/style.css') }}">

<!-- Custom CSS File -->
@stack('links')

resources/views/layouts/admin/components/navbar.blade.php
<nav class="navbar navbar-expand-lg main-navbar">
    <form class="form-inline mr-auto">
        <ul class="navbar-nav mr-3">
        <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
        <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i class="fas fa-search"></i></a></li>
        </ul>
        <div class="search-element">
        <input class="form-control" type="search" placeholder="Search" aria-label="Search" data-width="250">
        <button class="btn" type="submit"><i class="fas fa-search"></i></button>
        </div>
    </form>
    <ul class="navbar-nav navbar-right">
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                <img alt="image" src="{{ asset('assets/img/avatar/avatar-1.png') }} class="rounded-circle mr-1">
                <div class="d-sm-none d-lg-inline-block">Hi, {{$me->name}}</div>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                <div class="dropdown-title" style="font-size: 8px">Logged in 5min</div>
                    <a href="{{route('admin.my-profile', $me->id)}}" class="dropdown-item has-icon">
                        <i class="far fa-user"></i> Profile
                    </a>
                    <a href="features-activities.html" class="dropdown-item has-icon">
                        <i class="fas fa-bolt"></i> Activities
                    </a>
                    <a href="{{route('admin.password', $me->id)}}" class="dropdown-item has-icon">
                        <i class="fas fa-key"></i> Change Password
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="{{ route('logout') }}" class="dropdown-item has-icon text-danger"
                        onclick="event.preventDefault();
                            document.getElementById('logout-form').submit();">
                        <i class="fas fa-sign-out-alt"></i> 
                        {{ __('Logout') }}
                    </a>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                        @csrf
                    </form>
            </div>
        </li>
    </ul>
</nav>

resources/views/layouts/admin/components/plugin.blade.php
<!-- General JS Scripts -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script src="{{ asset('assets/js/stisla.js') }}"></script>

<!-- Template JS File -->
<script src="{{ asset('assets/js/scripts.js') }}"></script>
<script src="{{ asset('assets/js/custom.js') }}"></script>

<!-- Custom JS File -->
@stack('scripts')

resources/views/layouts/admin/components/sidebar_menu.blade.php
<div class="main-sidebar">
    <aside id="sidebar-wrapper">
      <div class="sidebar-brand">
        <a href="{{route('home')}}">{{ config('app.name') }}</a>
      </div>
      <div class="sidebar-brand sidebar-brand-sm">
        <a href="{{route('home')}}">FN</a>
      </div>
      <ul class="sidebar-menu">
          <li class="menu-header">Dashboard Menu</li>
          <li class="nav-item dropdown">
          <a href="{{route('admin.dashboard')}}" class="nav-link {{ Request::is('dashboard') ? ' active' : null }}"><i class="fas fa-fire"></i><span>Dashboard</span></a>
          </li>
          <li class="menu-header">Starter</li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link has-dropdown" data-toggle="dropdown"><i class="fas fa-newspaper"></i> <span>Post</span></a>
            <ul class="dropdown-menu">
              <li><a class="nav-link beep beep-sidebar" href="#"><i class="far fa-plus-square" style="margin: 0"></i>Add Post</a></li>
              <li><a class="nav-link" href="#"><i class="fas fa-list-ul" style="margin: 0"></i>List Post</a></li>
              <li><a class="nav-link" href="#"><i class="fas fa-list-ul" style="margin: 0"></i>Draft Post</a></li>
              <li><a class="nav-link" href="#"><i class="far fa-comment" style="margin: 0"></i>Post Comment</a></li>
              <li><a class="nav-link" href="#"><i class="far fa-comments" style="margin: 0"></i>Post Comment reply</a></li>
            </ul>
          </li>
          
          <li class="nav-item dropdown">
            <a href="#" class="nav-link has-dropdown" data-toggle="dropdown"><i class="fas fa-stream"></i> <span>Kategory</span></a>
            <ul class="dropdown-menu">
              <li><a class="nav-link beep beep-sidebar" href="#"><i class="far fa-plus-square" style="margin: 0"></i>Add Kategory</a></li>
              <li><a class="nav-link" href="#"><i class="fas fa-list-ul" style="margin: 0"></i>List Kategory</a></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link has-dropdown" data-toggle="dropdown"><i class="fab fa-slack-hash"></i> <span>Tag</span></a>
            <ul class="dropdown-menu">
              <li><a class="nav-link beep beep-sidebar" href="#"><i class="far fa-plus-square" style="margin: 0"></i>Add Tags</a></li>
              <li><a class="nav-link" href="#"><i class="fas fa-list-ul" style="margin: 0"></i>List Tags</a></li>
            </ul>
          </li>
            <li class="menu-header">SDM & Permissions</li>
            <li><a class="nav-link" href="{{route('admin.users.index')}}"><i class="fas fa-user"></i> <span>Users</span></a></li>
            <li><a class="nav-link" href="{{route('admin.role.index')}}"><i class="fas fa-eye-slash"></i> <span>Roles</span></a></li>
            <li><a class="nav-link" href="{{route('admin.permission.index')}}"><i class="fas fa-info"></i> <span>Permissions</span></a></li>
            <li><a class="nav-link" href="#"><i class="far fa-trash-alt"></i> <span>Trash Bin</span></a></li>
        </ul>

        <div class="mt-4 mb-4 p-3 hide-sidebar-mini">
          <a href="{{ url('/') }}" class="btn btn-primary btn-lg btn-block btn-icon-split">
            <i class="fas fa-rocket"></i> {{ config('app.name') }}
          </a>
        </div> 
    </aside>
  </div>