routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\MyProfileController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\RoleController;



Route::prefix('admin')->name('admin.')->group(function () {
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('users', UserController::class);

    Route::get('users/{id}/my-profiles',         [MyProfileController::class, 'index'])->name('my-profile');
    Route::get('users/{id}/my-profiles-edit',    [MyProfileController::class, 'profile'])->name('my-profile.edit');
    Route::put('users/{id}/my-profiles-update',  [MyProfileController::class, 'updateProfile'])->name('my-profile.update');
    Route::get('users/{id}/password',            [MyProfileController::class, 'Password'])->name('password');
    Route::put('users/{id}/change-password',     [MyProfileController::class, 'changePassword'])->name('change-password');

    Route::resource('permission', PermissionController::class);
    Route::resource('role', RoleController::class);
});

routes/web.php
<?php

// use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    return view('welcome');
});

// Route::get('export/excel', [UserController::class, 'exportExcel'])->name('excel');
// Route::get('export/csv', [UserController::class, 'exportCsv'])->name('csv');
// Route::get('export/pdf', [UserController::class, 'exportPdf'])->name('pdf');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

require __DIR__.'/admin.php';

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasFactory, Notifiable, HasRoles;

    // this code will define user's guard   
    protected $guard = 'web';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'username',
        'address',
        'phone',
        'avatar',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\UserRequest;
use App\Http\Requests\UserUpdateRequest;
use App\Repositories\RoleRepository;
use App\Repositories\UserRepository;

class UserController extends Controller
{

    protected $userRepository;
    protected $roleRepository;

    public function __construct(UserRepository $userRepository,
                                RoleRepository $roleRepository)
    {
        $this->user = $userRepository;
        $this->role = $roleRepository;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = $this->user->getAll();
        return view('admin.user.index', compact('user'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = $this->role->getAll();
        return view('admin.user.form', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {
        $this->user->store($request);
        return redirect('admin/users')->withSuccess('You have successfully added a new user');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = $this->user->getById($id);
        $getUserByRoles = $this->user->getUserByRoles($id);
        $roles = $this->role->getAll();
        return view('admin.user.form', compact('user', 'roles', 'getUserByRoles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserUpdateRequest $request, $id)
    {
        $this->user->updateById($id);
        return redirect()->back()->withSuccess('You have successfully updated a user');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/user/changePassword.blade.php
@extends('layouts.admin.app')
@section('sub-title', 'Management Password')
@section('location', 'Management Password')
@section('content') 
<div class="card">
    <form action="{{route('admin.change-password', $user->id)}}" method="POST">
    @csrf
    @method('PUT')
    <div class="card-header">
        <h4>Change Password</h4>
    </div>
    <div class="card-body">
        <div class="form-group">
          <label for="email">Email</label>
          <input type="email" name="email" class="form-control" placeholder="{{$user->email}}" disabled>
        </div>
        <div class="form-group">
            <label for="old_password">Old Password</label>
            <div class="input-group">
                <input type="password" name="old_password" class="form-control">
                <div class="input-group-text toggle-password">
                    <i class="fa fa-fw fa-eye-slash"></i>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="password">New Password</label>
                <div class="input-group">
                    <input type="password" name="password" id="password" class="form-control" placeholder="Create New Password ...">
                    <div class="input-group-text toggle-password">
                        <i class="fa fa-fw fa-eye-slash"></i>
                    </div>
                </div>
            </div>
            <div class="form-group col-md-6">
                <label for="confirm_password">Password Confirm</label>
                <div class="input-group">
                    <input type="password" name="confirm_password" id="confirm_password" class="form-control" placeholder="Confirm New Password ...">
                    <div class="input-group-text toggle-password">
                        <i class="fa fa-fw fa-eye-slash"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card-footer">
      <button type="submit" class="btn btn-primary">Submit</button>
      <a href="{{route('admin.my-profile', $me->id)}}" class="btn btn-warning">Back</a>
    </div>
    </form>
</div>
@endsection
@push('scripts')
<script>
// View Password
$('.toggle-password').click(function(){
    $(this).children().toggleClass('fa-eye-slash fa-eye');
    let input = $(this).prev();
    input.attr('type', input.attr('type') === 'password' ? 'text' : 'password');
});    
</script>    
@endpush

resources/views/admin/user/changeProfile.blade.php
@extends('layouts.admin.app')
@section('sub-title', 'Profile')
@section('location', 'Edit Profile')  
@push('links')
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css"> 
@endpush
@section('content') 
<div class="card">
    <form action="{{route('admin.my-profile.update', $user->id)}}"
    method="POST">
    @csrf
    @method('PUT')
    <div class="card-header">
        <h4><a href="{{url('admin/users/'.$user->id.'/my-profiles')}}" class="btn btn-warning">Back</a></h4>
        @if (!(get_action_name() == 'create'))
        <div class="card-header-action">
            <div class="dropdown">
              <a href="#" class="dropdown-toggle btn btn-primary" data-toggle="dropdown" aria-expanded="false">Advanced</a>
              <div class="dropdown-menu dropdown-menu-right" x-placement="bottom-end" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(70px, 25px, 0px);">
                <a href="{{route('admin.password', $user->id)}}" class="dropdown-item has-icon"><i class="fas fa-key"></i>Change Password</a>
              </div>
            </div>
        </div>
        @endif
    </div>
    <div class="card-body">
        <div class="form-row">
            <div class="form-group col-md-6">
              <label for="name">Name</label>
              <input type="text" name="name" class="form-control" placeholder="Create name.." value="{{ $user->name ?? '' }}">
            </div>
            <div class="form-group col-md-6">
              <label for="name">Username</label>
              <input type="text" name="username" class="form-control" placeholder="Create username.." value="{{ $user->username ?? '' }}">
            </div>
        </div>
        <div class="form-row">
            <div class="{{(get_action_name() == 'create')? 'form-group col-md-6': 'form-group col-md-12'}}">
            <label for="email">Email</label>
            <input type="email" class="form-control" name="email" placeholder="Email" value="{{ $user->email ?? '' }}">
            </div>
        </div>
        <div class="form-group">
            <label for="address">Address</label>
            <input type="text" name="address" class="form-control" placeholder="Apartment, studio, or floor" value="{{$user->address ?? ''}}">
        </div>
        <div class="form-group">
            <label for="phone">Phone Number</label>
            <input type="text" name="phone" class="form-control" placeholder="0896-XXXX-XXXX" value="{{$user->phone ?? ''}}">
        </div>
    </div>
    <div class="card-footer">
      <button type="submit" class="btn btn-primary">
          {{(get_action_name() == 'create') ? 'Submit': 'Update'}}
      </button>
    </div>
    </form>
</div>
@endsection
@push('scripts')
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
<script>
// View Password
$('.toggle-password').click(function(){
    $(this).children().toggleClass('fa-eye-slash fa-eye');
    let input = $(this).prev();
    input.attr('type', input.attr('type') === 'password' ? 'text' : 'password');
});
</script>
@endpush

resources/views/admin/user/form.blade.php
@extends('layouts.admin.app')
@section('sub-title', 'Profile')

@section('location')  
@if (get_action_name() == 'create')
Add User
@else
Edit User
@endif
@endsection

@push('links')
<style>
    .isDisabled {
        cursor: not-allowed;
        opacity: 0.5;
        color: red;
    }
</style>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css"> 
@endpush
@section('content') 
<div class="card">
    <form action="{{
    route((get_action_name() == 'create')? 'admin.users.store': 'admin.users.update', [
        'user'   => $user ?? '',
        ])
    }}" 
    method="POST">
    @csrf
    @method((get_action_name() == 'create') ? 'POST': 'PUT')

    <div class="card-header">
        <h4><a href="{{route('admin.users.index')}}" class="btn btn-warning">Back</a></h4>
        @if (!(get_action_name() == 'create'))
        <div class="card-header-action">
            <div class="dropdown">
              <a href="#" class="dropdown-toggle btn btn-primary" data-toggle="dropdown" aria-expanded="false">Advanced</a>
              <div class="dropdown-menu dropdown-menu-right" x-placement="bottom-end" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(70px, 25px, 0px);">
                @if ( $user->id != $me->id )
                <a href="javascript:void(0)" class="dropdown-item has-icon isDisabled"><i class="fas fa-user-times"></i>You don't have access</a>
                @else
                <a href="{{route('admin.password', $user->id)}}" class="dropdown-item has-icon"><i class="fas fa-key"></i>Change Password</a>
                @endif
              </div>
            </div>
        </div>
        @endif
    </div>
    <div class="card-body">
        <div class="form-row">
            <div class="form-group col-md-6">
              <label for="name">Name</label>
              <input type="text" name="name" class="form-control" placeholder="Create name.." value="{{ $user->name ?? '' }}" required>
            </div>
            <div class="form-group col-md-6">
              <label for="name">Username</label>
              <input type="text" name="username" class="form-control" placeholder="Create username.." value="{{ $user->username ?? '' }}" required>
            </div>
        </div>
        <div class="form-row">
            <div class="{{(get_action_name() == 'create')? 'form-group col-md-6': 'form-group col-md-12'}}">
            <label for="email">Email</label>
            <input type="email" class="form-control" name="email" placeholder="Email" value="{{ $user->email ?? '' }}">
            </div>
            @if ((get_action_name() == 'create'))
            <div class="form-group col-md-6">
                <label for="password">Password</label>
                <div class="input-group">
                    <input type="password" name="password" id="password" class="form-control" placeholder="Password" value="{{ $user->password ?? '' }}" required>
                    <div class="input-group-text toggle-password">
                        <i class="fa fa-fw fa-eye-slash"></i>
                    </div>
                </div>
            </div>
            @endif
        </div>
        <div class="form-group">
            <label for="address">Address</label>
            <input type="text" name="address" class="form-control" placeholder="Apartment, studio, or floor" value="{{$user->address ?? ''}}">
        </div>
        <div class="form-group">
            <label for="phone">Phone Number</label>
            <input type="text" name="phone" class="form-control" placeholder="0896-XXXX-XXXX" value="{{$user->phone ?? ''}}">
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="status">Status</label>
                <select class="selectpicker form-control" name="status" required>
                    <option name="status" value="1" {{ ($user->status ?? '') == '1' ? 'selected': '' }}>Active</option>
                    @if ((get_action_name() !== 'create'))
                    @role('super_admin|admin')
                    <option value="0" {{ ($user->status ?? '') == '0' ? 'selected': '' }}>Inactive</option>
                    @else
                    {{-- if not super_admin|admin not a option... --}}
                    @endrole
                    @endif
                </select>
            </div>
            <div class="form-group col-md-6">
                <label for="inputAddress2">Roles</label>
                <select class="selectpicker form-control" data-live-search="true" name="roles[]">
                    <option value="" disabled selected>Select your role</option>
                    @if (get_action_name() == 'create')
                        @foreach ($roles as $role)
                        <option value="{{$role->name}}">{{$role->display_name}}</option>
                        @endforeach
                    @else
                        @foreach ($roles as $role)
                        <option value="{{$role->name}}" 
                            @foreach ($getUserByRoles as $item)
                                @if ($role->name == $item)
                                    selected
                                @endif
                            @endforeach    
                        >{{$role->display_name}}</option>
                        @endforeach
                    @endif
                </select>
            </div>
        </div>
    </div>
    <div class="card-footer">
      <button type="submit" class="btn btn-primary">
          {{(get_action_name() == 'create') ? 'Submit': 'Update'}}
      </button>
    </div>
    </form>
</div>
@endsection
@push('scripts')
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>

<script>
// View Password
$('.toggle-password').click(function(){
    $(this).children().toggleClass('fa-eye-slash fa-eye');
    let input = $(this).prev();
    input.attr('type', input.attr('type') === 'password' ? 'text' : 'password');
});
</script>
@endpush

resources/views/admin/user/index.blade.php
@extends('layouts.admin.app')
@section('sub-title', 'User')
@section('location', 'User')
@push('links')
<!-- MDBootstrap Datatables  -->
<link href="{{asset('assets/css/datatables.min.css')}}" rel="stylesheet">
@endpush
@section('content') 
    <div class="card">
        <div class="card-header">
            <h4><a href="{{route('admin.users.create')}}" class="btn btn-info">Create User</a></h4>
            <div class="card-header-action" style="display: flex">
              <form action="{{route('admin.users.index')}}" method="get">
                <div class="input-group">
                  <input type="text" name="filter[name]" class="form-control" placeholder="Search by name" value="">
                  <div class="input-group-btn">
                    <button type="submit" class="btn btn-primary"><i class="fas fa-search"></i></button>
                  </div>
                </div>
              </form>
              <div class="card-header-action dropdown" style="margin-left: 2em">
                <a href="#" data-toggle="dropdown" class="btn btn-danger dropdown-toggle" aria-expanded="false">Select</a>
                <ul class="dropdown-menu dropdown-menu-sm dropdown-menu-right" x-placement="bottom-end" style="position: absolute; transform: translate3d(75px, 31px, 0px); top: 0px; left: 0px; will-change: transform;">
                  <li class="dropdown-title">Select by</li>
                  <li><a href="#" class="dropdown-item">Username</a></li>
                  <li><a href="#" class="dropdown-item">Name</a></li>
                  <li><a href="#" class="dropdown-item">Roles</a></li>
                  <li><a href="#" class="dropdown-item">Join On</a></li>
                </ul>
              </div>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
              <table class="table table-striped" id="table-user">
                <thead>
                  <tr>
                    <th class="text-center">
                      <div class="custom-checkbox custom-control">
                        <input type="checkbox" data-checkboxes="mygroup" data-checkbox-role="dad" class="custom-control-input" id="checkbox-all" onclick="toggle(this);">
                        <label for="checkbox-all" class="custom-control-label">&nbsp;</label>
                      </div>
                    </th>
                    <th>Username</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Profile</th>
                    <th>Join On</th>
                    <th>Roles</th>
                    <th>Action</th>
                  </tr>
                </thead>
                @if (count($user) > 0)
                @foreach ($user as $data)
                <tbody>
                  <tr>
                    <td>
                      <div class="custom-checkbox custom-control">
                        <input type="checkbox" data-checkboxes="mygroup" class="custom-control-input" id="checkbox-1">
                        <label for="checkbox-1" class="custom-control-label">&nbsp;</label>
                      </div>
                    </td>
                    <td>{{$data->username}}</td>
                    <td>{{$data->name}}</td>
                    <td>{{$data->email}}</td>
                    <td>
                      <img alt="image" src="../assets/img/avatar/avatar-5.png" class="rounded-circle" width="35" data-toggle="tooltip" title="" data-original-title="Wildan Ahdian">
                    </td>
                    <td>{{$data->created_at->format('d/m/Y')}}</td>
                    <td>
                      @forelse ($data->roles as $item)
                        <div class="badge badge-light">{{$item->display_name}}</div>
                      @empty
                        <div class="badge badge-danger">No Roles</div>
                      @endforelse
                    </td>
                    <td>
                      <a href="#" class="btn btn-sm btn-info trigger--fire-modal-6" data-toggle="modal" data-target="#users{{$data->id}}">Detail</a>
                      <a href="{{route('admin.users.edit', $data->id)}}" class="btn btn-sm btn-primary">Edit</a>
                    </td>
                  </tr>
                </tbody>
                @endforeach
                @else
                <td colspan="9" class="text-center"><h4>User is not Found!</h4></td>
                @endif
            </table>
          </div>
        </div>
    </div>

    <!-- Pagination -->
    <nav aria-label="Page navigation example">
      <ul class="pagination">
        <li class="page-item">
          {{$user->links('vendor.pagination.bootstrap-4')}}
        </li>
      </ul>
    </nav>
@endsection
@section('modal')
<!-- Modal -->
@foreach ($user as $data)
<div class="modal fade" id="users{{$data->id}}" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="exampleModalLabel" style="color: #6777ef">Details:</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="form-group row">
          <label for="name" class="col-sm-2 col-form-label">Name</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" value="{{$data->name}}" disabled>
          </div>
        </div>
        <div class="form-group row">
          <label for="username" class="col-sm-2 col-form-label">Username</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" value="{{$data->username}}" disabled>
          </div>
        </div>
        <div class="form-group row">
          <label for="inputEmail3" class="col-sm-2 col-form-label">Email</label>
          <div class="col-sm-10">
            <input type="email" class="form-control" value="{{$data->email}}" disabled>
          </div>
        </div>
        <div class="form-group row">
          <label for="address" class="col-sm-2 col-form-label">Address</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" value="{{$data->address ?? 'Address not found'}}" disabled>
          </div>
        </div>
        <div class="form-group row">
          <label for="phone" class="col-sm-2 col-form-label">Phone</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" value="{{$data->phone ?? 'Phone number not found'}}" disabled>
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="status">Status</label>
            <input type="text" name="status" class="form-control" 
            value="{{($data->status ?? '') == 1 ? 'Active':'Inactive'}}"
            disabled>
          </div>
          <div class="form-group col-md-6">
            <label for="roles">Roles</label>
            @forelse ($data->roles as $item)
              <input type="text" name="roles" class="form-control" value="{{$item->display_name}}" disabled>
            @empty
              <input type="text" name="roles" class="form-control" value="No Roles" disabled>
            @endforelse
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
        <a href="{{route('admin.users.edit', $data->id)}}" class="btn btn-primary">Edit</a>
      </div>
    </div>
  </div>
</div>
@endforeach
@endsection
@push('scripts')
<!-- MDBootstrap Datatables  -->
<script type="text/javascript" src="{{asset('assets/js/pages/datatables.min.js')}}"></script>
<script>
  // Selected All Cheackbox
$(document).ready(function () {
$('#table-user').DataTable();
$('.dataTables_length').addClass('bs-select');
});
  // Selected All Cheackbox
function toggle(source) {
    var checkboxes = document.querySelectorAll('input[type="checkbox"]');
    for (var i = 0; i < checkboxes.length; i++) {
        if (checkboxes[i] != source)
            checkboxes[i].checked = source.checked;
    }
};
</script>
@endpush